# Generated by Django 4.2 on 2023-04-25 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Data", "0003_alter_product_ratings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="ratings",
        ),
    ]
